#include <iostream>
#include <string>
using namespace std;
int main()
{
	std::cout<<"Hola, vamos a hacer unas operaciones matematiacas basicas, 5 por cada operador. Oprime enter para continuar: "<<std::endl;
	std::cin.ignore();
	std::cout<<std::endl;
	double num1a, num1b, num2a, num2b, num3a, num3b, num4a, num4b, num5a, num5b;
	double suma1, suma2, suma3, suma4, suma5;
	double resta1, resta2, resta3, resta4, resta5;
	double multiplicacion1, multiplicacion2, multiplicacion3, multiplicacion4, multiplicacion5;
	double division1, division2, division3, division4, division5;
	int res_num1a, res_num1b, res_num2a, res_num2b, res_num3a, res_num3b, res_num4a, res_num4b, res_num5a, res_num5b;
    int residuo1, residuo2, residuo3, residuo4, residuo5;	 
	std::cout<<"vamos a empezar con 5 SUMAS: "<<std::endl;
	std::cout<<endl;
	std::cout <<"Ingrese el numero A de la suma 1: ";
	std::cin >> num1a;
	std::cout << "Ingrese el numero B de la suma 1: ";
	std::cin >> num1b;
	suma1=num1a+num1b;
	std::cout << "El resultado de la primera operacion es: "<<suma1<<std::endl;
	std::cout<<std::endl;
	std::cout << "Ingrese el numero A de la suma 2: ";
	std::cin >> num2a;
	std::cout <<"Ingrese el numero B de la suma 2: ";
	std::cin >> num2b;
	suma2=num2a+num2b;
	std::cout << "El resultado de la primera operacion es: "<<suma2<<std::endl;
	std::cout<<std::endl;
	std::cout <<"Ingrese el numero A de la suma 3: ";
	std::cin >> num3a;
	std::cout << "Ingrese el numero B de la suma 3: ";
	std::cin >> num3b;
	suma3=num3a+num3b;
	std::cout << "El resultado de la primera operacion es: "<<suma3<<std::endl;
	std::cout<<std::endl;
	std::cout << "Ingrese el numero A de la suma 4: ";
	std::cin >> num4a;
	std::cout <<"Ingrese el numero B de la suma 4: ";
	std::cin >> num4b;
	suma4=num4a+num4b;
	std::cout << "El resultado de la primera operacion es: "<<suma4<<std::endl;
	std::cout<<std::endl;
	std::cout << "Ingrese el numero A de la suma 5: ";
	std::cin >> num5a;
	std::cout <<"Ingrese el numero B de la suma 5: ";
	std::cin >> num5b;
	suma5=num5a+num5b;
	std::cout << "El resultado de la primera operacion es: "<<suma5<<std::endl;
	std::cout<<std::endl;
	
	std::cout<<"Ahora vamos a hacer 5 RESTAS"<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el minuendo para la resta 1: ";
	std::cin>>num1a;
	std::cout<<"Ingrese el sustraendo para la resta 1: ";
	std::cin>>num1b;
	resta1=num1a-num1b;
	std::cout<<"El resultado de la primera resta es: "<<resta1<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el minuendo para la resta 2: ";
	std::cin>>num2a;
	std::cout<<"Ingrese el sustraendo para la resta 2: ";
	std::cin>>num2b;
	resta2=num2a-num2b;
	std::cout<<"El resultado de la segunda resta es: "<<resta2<<std::endl;
	std::cout<<std::endl;
	resta2=num2a-num2b;
	std::cout<<"Ingrese el minuendo para la resta 3: ";
	std::cin>>num3a;
	std::cout<<"Ingrese el sustraendo para la resta 3: ";
	std::cin>>num3b;
	resta3=num3a-num3b;
	std::cout<<"El resultado de la tercera resta es: "<<resta3<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el minuendo para la resta 4: ";
	std::cin>>num4a;
	std::cout<<"Ingrese el sustraendo para la resta 4: ";
	std::cin>>num4b;
	resta4=num4a-num4b;
	std::cout<<"El resultado de la cuarta resta es: "<<resta4<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el minuendo para la resta 5: ";
	std::cin>>num5a;
	std::cout<<"Ingrese el sustraendo para la resta 5: ";
	std::cin>>num5b;
	resta5=num5a-num5b;
	std::cout<<"El resultado de la quinta resta es: "<<resta5<<std::endl;
	std::cout<<std::endl;
	
	std::cout<<"Ahora vamos a hacer 5 MULTIPLICACIONES"<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el multiplicando de la operacion 1: ";
	std::cin>>num1a;
	std::cout<<"Ingrese el Multiplicador de la operacion 1: ";
	std::cin>>num1b;
	multiplicacion1=num1a*num1b;
	std::cout<<"El resultado de la multiplicacion 1 es: "<<multiplicacion1<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el multiplicando de la operacion 2: ";
	std::cin>>num2a;
	std::cout<<"Ingrese el Multiplicador de la operacion 2: ";
	std::cin>>num2b;
	multiplicacion2=num2a*num2b;
	std::cout<<"El resultado de la multiplicacion 2 es: "<<multiplicacion2<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el multiplicando de la operacion 3: ";
	std::cin>>num3a;
	std::cout<<"Ingrese el Multiplicador de la operacion 3: ";
	std::cin>>num3b;
	multiplicacion3=num3a*num3b;
	std::cout<<"El resultado de la multiplicacion 3 es: "<<multiplicacion3<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el multiplicando de la operacion 4: ";
	std::cin>>num4a;
	std::cout<<"Ingrese el Multiplicador de la operacion 4: ";
	std::cin>>num4b;
	multiplicacion4=num4a*num4b;
	std::cout<<"El resultado de la multiplicacion 4 es: "<<multiplicacion4<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el multiplicando de la operacion 5: ";
	std::cin>>num5a;
	std::cout<<"Ingrese el Multiplicador de la operacion 5: ";
	std::cin>>num5b;
	multiplicacion5=num5a*num5b;
	std::cout<<"El resultado de la multiplicacion 5 es: "<<multiplicacion5<<std::endl;
	std::cout<<std::endl;
	
	std::cout<<"Ahora vamos a hacer 5 DIVISIONES"<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el DIVIDENDO de la operacion 1: ";
	std::cin>>num1a;
	std::cout<<"Ingrese el DIVISOR de la operacion 1: ";
	std::cin>>num1b;
	division1=num1a/num1b;
	std::cout<<"El resultado de la DIVISION 1 es: "<<division1<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el DIVIDENDO de la operacion 2: ";
	std::cin>>num2a;
	std::cout<<"Ingrese el DIVISOR de la operacion 2: ";
	std::cin>>num2b;
	division2=num2a/num2b;
	std::cout<<"El resultado de la DIVISION 2 es: "<<division2<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el DIVIDENDO de la operacion 3: ";
	std::cin>>num3a;
	std::cout<<"Ingrese el DIVISOR de la operacion 3: ";
	std::cin>>num3b;
	division3=num3a/num3b;
	std::cout<<"El resultado de la DIVISION 3 es: "<<division3<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el DIVIDENDO de la operacion 4: ";
	std::cin>>num4a;
	std::cout<<"Ingrese el DIVISOR de la operacion 4: ";
	std::cin>>num4b;
	division4=num4a/num4b;
	std::cout<<"El resultado de la DIVISION 4 es: "<<division4<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el DIVIDENDO de la operacion 5: ";
	std::cin>>num5a;
	std::cout<<"Ingrese el DIVISOR de la operacion 5: ";
	std::cin>>num5b;
	division5=num5a/num5b;
	std::cout<<"El resultado de la DIVISION 5 es: "<<division5<<std::endl;
	std::cout<<std::endl;
	std::cin.ignore();
	std::cout<<std::endl;
	
	std::cout<<std::endl;
	std::cout<<"Ahora vamos a hallar el RESIDUO en 5 opereciones "<<std::endl;
	std::cout<<"Ingrese el DIVIDENDO de la operacion 1: ";
	std::cin>>res_num1a;
	std::cout<<"Ingrese el DIVISOR de la operacion 1: ";
	std::cin>>res_num1b;
	residuo1 = res_num1a%res_num1b;
	std::cout<<"El resultado de la DIVISION 1 es: "<<residuo1<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el DIVIDENDO de la operacion 2: ";
	std::cin>>res_num2a;
	std::cout<<"Ingrese el DIVISOR de la operacion 2: ";
	std::cin>>res_num2b;
	residuo2= res_num2a%res_num2b;
	std::cout<<"El resultado de la DIVISION 2 es: "<<residuo2<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el DIVIDENDO de la operacion 3: ";
	std::cin>>res_num3a;
	std::cout<<"Ingrese el DIVISOR de la operacion 3: ";
	std::cin>>res_num3b;
	residuo3 = res_num3a%res_num1b;
	std::cout<<"El resultado de la DIVISION 1 es: "<<residuo1<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el DIVIDENDO de la operacion 1: ";
	std::cin>>res_num1b;
	std::cout<<"Ingrese el DIVISOR de la operacion 1: ";
	std::cin>>res_num1b;
	residuo1 = res_num1b%res_num1b;
	std::cout<<"El resultado de la DIVISION 1 es: "<<residuo1<<std::endl;
	std::cout<<std::endl;
	std::cout<<"Ingrese el DIVIDENDO de la operacion 1: ";
	std::cin>>res_num1b;
	std::cout<<"Ingrese el DIVISOR de la operacion 1: ";
	std::cin>>res_num1b;
	residuo1 = res_num1b%res_num1b;
	std::cout<<"El resultado de la DIVISION 1 es: "<<residuo1<<std::endl;
	std::cout<<std::endl;	
	std::cin.ignore();
	std::cout<<std::endl;
	std:cout<<"GRACIAS!!";
	getchar ();
	return 0;
}
