#include <iostream>
#include <string>
using namespace std;
int main()
{
	std::cout<<"Hola, vamos a hacer unas operaciones logicas. Oprime enter para continuar: "<<std::endl;
	std::cin.ignore();
	double num1a, num1b, num2a, num2b, num3a, num3b, num4a, num4b, num5a, num5b;
	double compara1, compara2, compara3, compara4, compara5; 
	double igualdad1, igualdad1, igualdad1, igualdad5, igualdad5, 
	std::cout<<"EJEMPLO 1 A MENOR que B: "<<std::endl;
	std::cout<<endl;
	std::cout <<"Ingrese el numero A: ";
	std::cin >> num1a;
	std::cout << "Ingrese el numero B: ";
	std::cin >> num1b;
	compara1=num1a<num1b;
	std::cout << "El resultado de la primera operacion es: "<<compara1<<std::endl;
	std::cout<<std::endl;
	std::cout<<"EJEMPLO 2 A MENOR que B: "<<std::endl;
	std::cout<<endl;
	std::cout <<"Ingrese el numero A: ";
	std::cin >> num2a;
	std::cout << "Ingrese el numero B: ";
	std::cin >> num2b;
	compara2=num2a<num2b;
	std::cout << "El resultado de la SEGUNDA operacion es: "<<compara2<<std::endl;
	std::cout<<std::endl;
	std::cout<<"EJEMPLO 3 A MENOR que B: "<<std::endl;
	std::cout<<endl;
	std::cout <<"Ingrese el numero A: ";
	std::cin >> num3a;
	std::cout << "Ingrese el numero B: ";
	std::cin >> num3b;
	compara3=num3a<num3b;
	std::cout << "El resultado de la TERCERA operacion es: "<<compara3<<std::endl;
	std::cout<<std::endl;
	std::cout<<"EJEMPLO 4 A MENOR que B: "<<std::endl;
	std::cout<<endl;
	std::cout <<"Ingrese el numero A: ";
	std::cin >> num4a;
	std::cout << "Ingrese el numero B: ";
	std::cin >> num4b;
	compara4=num4a<num4b;
	std::cout << "El resultado de la CUARTA operacion es: "<<compara4<<std::endl;
	std::cout<<std::endl;
	std::cout<<"EJEMPLO 5 A MENOR que B: "<<std::endl;
	std::cout<<endl;
	std::cout <<"Ingrese el numero A: ";
	std::cin >> num5a;
	std::cout << "Ingrese el numero B: ";
	std::cin >> num5b;
	compara5=num5a<num5b;
	std::cout << "El resultado de la QUINTA operacion es: "<<compara5<<std::endl;
	std::cout<<std::endl;
	
	std::cout<<"Ahora vamos a comparar si A es MAYOR que B: "<<std::endl;
	std::cin.ignore();
	std::cout<<"EJEMPLO 1 A MAYOR que B: "<<std::endl;
	std::cout<<endl;
	std::cout <<"Ingrese el numero A: ";
	std::cin >> num1a;
	std::cout << "Ingrese el numero B: ";
	std::cin >> num1b;
	compara1=num1a>num1b;
	std::cout << "El resultado de la primera operacion es: "<<compara1<<std::endl;
	std::cout<<std::endl;
	
	std::cout<<"Ahora vamos a comparar si A es es IGUAL que B: "<<std::endl;
	std::cin.ignore();
	std::cout<<"EJEMPLO 1 A IGUAL que B: "<<std::endl;
	std::cout<<endl;
	std::cout <<"Ingrese el numero A: ";
	std::cin >> num1a;
	std::cout << "Ingrese el numero B: ";
	std::cin >> num1b;
	igualdad1=num1a==num1b;
	std::cout << "El resultado de la primera operacion es: "<<igualdad1<<std::endl;
	std::cout<<std::endl;
	std::cout<<"EJEMPLO 2 A IGUAL que B: "<<std::endl;
	std::cout<<endl;
	std::cout <<"Ingrese el numero A: ";
	std::cin >> num2a;
	std::cout << "Ingrese el numero B: ";
	std::cin >> num2b;
	igualdad2==num2a>num2b;
	std::cout << "El resultado de la segunda operacion es: "<<igualdad2<<std::endl;
	std::cout<<std::endl;
	std::cout<<"EJEMPLO 3 A IGUAL que B: "<<std::endl;
	std::cout<<endl;
	std::cout <<"Ingrese el numero A: ";
	std::cin >> num3a;
	std::cout << "Ingrese el numero B: ";
	std::cin >> num3b;
	igualdad3==num3a>num3b;
	std::cout << "El resultado de la tercera operacion es: "<<igualdad3<<std::endl;
	std::cout<<std::endl;
	std::cout<<"EJEMPLO 4 A IGUAL que B: "<<std::endl;
	std::cout<<endl;
	std::cout <<"Ingrese el numero A: ";
	std::cin >> num4a;
	std::cout << "Ingrese el numero B: ";
	std::cin >> num4b;
	igualdad4=num4a==num4b;
	std::cout << "El resultado de la cuarta operacion es: "<<igualdad4<<std::endl;
	std::cout<<std::endl;
	std::cout<<"EJEMPLO 5 A IGUALDAD que B: "<<std::endl;
	std::cout<<endl;
	std::cout <<"Ingrese el numero A: ";
	std::cin >> num5a;
	std::cout << "Ingrese el numero B: ";
	std::cin >> num5b;
	igualdad5=num5a==num5b;
	std::cout << "El resultado de la quinta operacion es: "<<igualdad5<<std::endl;
	std::cout<<std::endl;
}
